language: ruby
rvm:
- 2.0

before_script:
 - chmod +x ./script/*

script: ./script/cibuild.sh

after_success:
 - ./script/cideploy.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer